SELECT
CASE [hazardrate]
    WHEN 'INTERVALDECEASED' THEN
        1000
    WHEN 'INTERVALEMIGRATE' THEN
        30
    WHEN 'LIVENEWBORNS' THEN
        10
    WHEN 'AMBULATORYMINUTES' THEN
        24
    WHEN 'AMBULATORYVISITS' THEN
        2
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        12
    WHEN 'AMBULATORYSITEDAYS' THEN
        2
    WHEN 'AMBULATORYDAYS' THEN
        2
    WHEN 'AMBULATORYPERCENTUTILIZATION' THEN
        100
    WHEN 'INPATIENTDAYS' THEN
        30
    WHEN 'INPATIENTADMISSIONS' THEN
        1000
    WHEN 'INPATIENTDISCHARGES' THEN
        1000
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        60
    WHEN 'INPATIENTSTAYS' THEN
        1000
    WHEN 'INPATIENTPERCENTUTILIZATION' THEN
        100
    WHEN 'CAREMANAGERDAYS' THEN
        365
    WHEN 'CAREMANAGERALLOCATIONS' THEN
        1000
    WHEN 'CAREMANAGERRELEASES' THEN
        1000
    WHEN 'CAREMANAGERLENGTH' THEN
        5
    WHEN 'CAREMANAGERS' THEN
        5
    WHEN 'CAREMANAGERPERCENTUTILIZATION' THEN
        100
    WHEN 'HOMECARESERVICES' THEN
        25
    WHEN 'HOMECAREVISITS' THEN
        25
    WHEN 'SERVICESPERVISIT' THEN
        5
    WHEN 'HOMECAREDAYS' THEN
        25
    WHEN 'HOMECAREPERCENTUTILIZATION' THEN
        100
    WHEN 'HOMECAREPROFESSIONALSERVICES' THEN
        25
    WHEN 'HOMECAREPROFESSIONALVISITS' THEN
        25
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        5
    WHEN 'HOMECAREPROFESSIONALDAYS' THEN
        25
    WHEN 'HOMECAREPROFESSIONALPERCENTUTILIZATION' THEN
        100
    WHEN 'HOMECARETRANSITIONSERVICES' THEN
        5
    WHEN 'HOMECARETRANSITIONVISITS' THEN
        2
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        5
    WHEN 'HOMECARETRANSITIONDAYS' THEN
        2
    WHEN 'HOMECARETRANSITIONPERCENTUTILIZATION' THEN
        100
    WHEN 'LABORATORYASSAYS' THEN
        100
    WHEN 'LABORATORYSITEDAYS' THEN
        5
    WHEN 'ASSAYSPERCOLLECTION' THEN
        50
    WHEN 'LABORATORYDAYS' THEN
        5
    WHEN 'LABORATORYPERCENTUTILIZATION' THEN
        100
    WHEN 'LONGTERMCAREDAYS' THEN
        365
    WHEN 'LONGTERMCAREADMISSIONS' THEN
        250
    WHEN 'LONGTERMCAREDISCHARGES' THEN
        250
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        25
    WHEN 'LONGTERMCARESTAYS' THEN
        1000
    WHEN 'LONGTERMCAREPERCENTUTILIZATION' THEN
        100
    WHEN 'PHARMACYDAILYDOSES' THEN
        10
    WHEN 'PHARMACYTHERAPEUTICS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'DOSESPERTHERAPY' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'ALLDOSESPERDISPENSEDPERSON' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYSITEDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYPERCENTDISPENSED' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYSTANDARDDAILYDOSES' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYSTANDARDTHERAPEUTICS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'STANDARDDOSESPERDISPENSEDPERSON' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYSTANDARDSITEDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYSTANDARDDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYPERCENTDISPENSEDSTANDARD' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYCONTROLLEDDAILYDOSES' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYCONTROLLEDTHERAPEUTICS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'CONTROLLEDDOSESPERDISPENSEDPERSON' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYCONTROLLEDSITEDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYCONTROLLEDDAYS' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PHARMACYPERCENTDISPENSEDCONTROLLED' THEN
        MAKEDATE(2008, 4, 1)
    WHEN 'PRIMARYCAREPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PRIMARYCAREPROVIDERDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERPROVIDER' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PRIMARYCAREDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PRIMARYCAREPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'ANESTHESIOLOGYPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'ANESTHESIOLOGISTSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'ANESTHESIOLOGYDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'ANESTHESIOLOGYPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'CONSULTPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'CONSULTPROVIDERDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERCONSULT' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'CONSULTDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'CONSULTPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'GENERALPRACTICEPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'GENERALPRACTITIONERSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'GENERALPRACTICEDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'GENERALPRACTICEPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'OBSTETRICPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'OBSTETRICIANSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'OBSTETRICDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'OBSTETRICPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PATHOLOGYPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PATHOLOGISTSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PATHOLOGYDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PATHOLOGYPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'RADIOLOGYPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'RADIOLOGISTSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'RADIOLOGYDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'RADIOLOGYPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SPECIALTYPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SPECIALISTSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SPECIALTYDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SPECIALTYPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SURGICALPROCEDURES' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SURGEONSDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'PROCEDURESPERSURGEON' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SURGERYDAYS' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SURGERYPERCENTUTILIZATION' THEN
        MAKEDATE(2001, 4, 1)
    WHEN 'SUPPORTIVELIVINGDAYS' THEN
        90
    WHEN 'SUPPORTIVELIVINGADMISSIONS' THEN
        200
    WHEN 'SUPPORTIVELIVINGDISCHARGES' THEN
        200
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        25
    WHEN 'SUPPORTIVELIVINGSTAYS' THEN
        500
    WHEN 'SUPPORTIVELIVINGPERCENTUTILIZATION' THEN
        100
    ELSE
        0
END