SELECT
CASE [hazardrate]
    WHEN 'INTERVALDECEASED' THEN
        SQRT(
            SUM([INTERVALDECEASED]^2) / SUM([INTERVALDECEASED])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INTERVALDECEASED] * [DURATIONDAYS]) / (SUM([INTERVALDECEASED]) * SUM([DURATIONDAYS]))
        )
    WHEN 'INTERVALEMIGRATE' THEN
        SQRT(
            SUM([INTERVALEMIGRATE]^2) / SUM([INTERVALEMIGRATE])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INTERVALEMIGRATE] * [DURATIONDAYS]) / (SUM([INTERVALEMIGRATE]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LIVENEWBORNS' THEN
        SQRT(
            SUM([LIVENEWBORNS]^2) / SUM([LIVENEWBORNS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LIVENEWBORNS] * [DURATIONDAYS]) / (SUM([LIVENEWBORNS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYMINUTES' THEN
        SQRT(
            SUM([AMBULATORYMINUTES]^2) / SUM([AMBULATORYMINUTES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYMINUTES] * [DURATIONDAYS]) / (SUM([AMBULATORYMINUTES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYVISITS' THEN
        SQRT(
            SUM([AMBULATORYVISITS]^2) / SUM([AMBULATORYVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYVISITS] * [DURATIONDAYS]) / (SUM([AMBULATORYVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        SQRT(
            SUM([AMBULATORYMINUTES]^2) / SUM([AMBULATORYMINUTES])^2
                + SUM([AMBULATORYVISITS]^2) / SUM([AMBULATORYVISITS])^2
                - 2 * SUM([AMBULATORYMINUTES] * [AMBULATORYVISITS]) / (SUM([AMBULATORYMINUTES]) * SUM([AMBULATORYVISITS]))
        )
    WHEN 'AMBULATORYSITEDAYS' THEN
        SQRT(
            SUM([AMBULATORYSITEDAYS]^2) / SUM([AMBULATORYSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYSITEDAYS] * [DURATIONDAYS]) / (SUM([AMBULATORYSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYDAYS' THEN
        SQRT(
            SUM([AMBULATORYDAYS]^2) / SUM([AMBULATORYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYDAYS] * [DURATIONDAYS]) / (SUM([AMBULATORYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([AMBULATORYVISITS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([AMBULATORYVISITS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([AMBULATORYVISITS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([AMBULATORYVISITS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPRIVATEMINUTES' THEN
        SQRT(
            SUM([AMBULATORYPRIVATEMINUTES]^2) / SUM([AMBULATORYPRIVATEMINUTES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYPRIVATEMINUTES] * [DURATIONDAYS]) / (SUM([AMBULATORYPRIVATEMINUTES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPRIVATEVISITS' THEN
        SQRT(
            SUM([AMBULATORYPRIVATEVISITS]^2) / SUM([AMBULATORYPRIVATEVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYPRIVATEVISITS] * [DURATIONDAYS]) / (SUM([AMBULATORYPRIVATEVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPRIVATELENGTHOFSTAY' THEN
        SQRT(
            SUM([AMBULATORYPRIVATEMINUTES]^2) / SUM([AMBULATORYPRIVATEMINUTES])^2
                + SUM([AMBULATORYPRIVATEVISITS]^2) / SUM([AMBULATORYPRIVATEVISITS])^2
                - 2 * SUM([AMBULATORYPRIVATEMINUTES] * [AMBULATORYPRIVATEVISITS]) / (SUM([AMBULATORYPRIVATEMINUTES]) * SUM([AMBULATORYPRIVATEVISITS]))
        )
    WHEN 'AMBULATORYPRIVATESITEDAYS' THEN
        SQRT(
            SUM([AMBULATORYPRIVATESITEDAYS]^2) / SUM([AMBULATORYPRIVATESITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYPRIVATESITEDAYS] * [DURATIONDAYS]) / (SUM([AMBULATORYPRIVATESITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPRIVATEDAYS' THEN
        SQRT(
            SUM([AMBULATORYPRIVATEDAYS]^2) / SUM([AMBULATORYPRIVATEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYPRIVATEDAYS] * [DURATIONDAYS]) / (SUM([AMBULATOAMBULATORYPRIVATEDAYSRYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([AMBULATORYPRIVATEVISITS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([AMBULATORYPRIVATEVISITS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([AMBULATORYPRIVATEVISITS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([AMBULATORYPRIVATEVISITS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYWORKMINUTES' THEN
        SQRT(
            SUM([AMBULATORYWORKMINUTES]^2) / SUM([AMBULATORYWORKMINUTES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYWORKMINUTES] * [DURATIONDAYS]) / (SUM([AMBULATORYWORKMINUTES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYWORKVISITS' THEN
        SQRT(
            SUM([AMBULATORYWORKVISITS]^2) / SUM([AMBULATORYWORKVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYWORKVISITS] * [DURATIONDAYS]) / (SUM([AMBULATORYWORKVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        SQRT(
            SUM([AMBULATORYWORKMINUTES]^2) / SUM([AMBULATORYWORKMINUTES])^2
                + SUM([AMBULATORYWORKVISITS]^2) / SUM([AMBULATORYWORKVISITS])^2
                - 2 * SUM([AMBULATORYWORKMINUTES] * [AMBULATORYWORKVISITS]) / (SUM([AMBULATORYWORKMINUTES]) * SUM([AMBULATORYWORKVISITS]))
        )
    WHEN 'AMBULATORYWORKSITEDAYS' THEN
        SQRT(
            SUM([AMBULATORYWORKSITEDAYS]^2) / SUM([AMBULATORYWORKSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYWORKSITEDAYS] * [DURATIONDAYS]) / (SUM([AMBULATORYWORKSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYWORKDAYS' THEN
        SQRT(
            SUM([AMBULATORYWORKDAYS]^2) / SUM([AMBULATORYWORKDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([AMBULATORYWORKDAYS] * [DURATIONDAYS]) / (SUM([AMBULATORYWORKDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'AMBULATORYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([AMBULATORYWORKVISITS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([AMBULATORYWORKVISITS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([AMBULATORYWORKVISITS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([AMBULATORYWORKVISITS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'INPATIENTDAYS' THEN
        SQRT(
            SUM([INPATIENTDAYS]^2) / SUM([INPATIENTDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INPATIENTDAYS] * [DURATIONDAYS]) / (SUM([INPATIENTDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'INPATIENTADMISSIONS' THEN
        SQRT(
            SUM([INPATIENTADMISSIONS]^2) / SUM([INPATIENTADMISSIONS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INPATIENTADMISSIONS] * [DURATIONDAYS]) / (SUM([INPATIENTADMISSIONS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'INPATIENTDISCHARGES' THEN
        SQRT(
            SUM([INPATIENTDISCHARGES]^2) / SUM([INPATIENTDISCHARGES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INPATIENTDISCHARGES] * [DURATIONDAYS]) / (SUM([INPATIENTDISCHARGES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        SQRT(
            SUM([INPATIENTDAYS]^2) / SUM([INPATIENTDAYS])^2
                + SUM([INPATIENTDISCHARGES]^2) / SUM([INPATIENTDISCHARGES])^2
                - 2 * SUM([INPATIENTDAYS] * [INPATIENTDISCHARGES]) / (SUM([INPATIENTDAYS]) * SUM([INPATIENTDISCHARGES]))
        )
    WHEN 'INPATIENTSTAYS' THEN
        SQRT(
            SUM([INPATIENTSTAYS]^2) / SUM([INPATIENTSTAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([INPATIENTSTAYS] * [DURATIONDAYS]) / (SUM([INPATIENTSTAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'INPATIENTPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([INPATIENTSTAYS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([INPATIENTSTAYS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([INPATIENTSTAYS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([INPATIENTSTAYS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'CAREMANAGERDAYS' THEN
        SQRT(
            SUM([CAREMANAGERDAYS]^2) / SUM([CAREMANAGERDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CAREMANAGERDAYS] * [DURATIONDAYS]) / (SUM([CAREMANAGERDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CAREMANAGERALLOCATIONS' THEN
        SQRT(
            SUM([CAREMANAGERALLOCATIONS]^2) / SUM([CAREMANAGERALLOCATIONS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CAREMANAGERALLOCATIONS] * [DURATIONDAYS]) / (SUM([CAREMANAGERALLOCATIONS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CAREMANAGERRELEASES' THEN
        SQRT(
            SUM([CAREMANAGERRELEASES]^2) / SUM([CAREMANAGERRELEASES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CAREMANAGERRELEASES] * [DURATIONDAYS]) / (SUM([CAREMANAGERRELEASES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CAREMANAGERLENGTH' THEN
        SQRT(
            SUM([CAREMANAGERDAYS]^2) / SUM([CAREMANAGERDAYS])^2
                + SUM([CAREMANAGERRELEASES]^2) / SUM([CAREMANAGERRELEASES])^2
                - 2 * SUM([CAREMANAGERDAYS] * [CAREMANAGERRELEASES]) / (SUM([CAREMANAGERDAYS]) * SUM([CAREMANAGERRELEASES]))
        )
    WHEN 'CAREMANAGERS' THEN
        SQRT(
            SUM([CAREMANAGERS]^2) / SUM([CAREMANAGERS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CAREMANAGERS] * [DURATIONDAYS]) / (SUM([CAREMANAGERS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CAREMANAGERPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([CAREMANAGERS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([CAREMANAGERS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([CAREMANAGERS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([CAREMANAGERS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECARESERVICES' THEN
        SQRT(
            SUM([HOMECARESERVICES]^2) / SUM([HOMECARESERVICES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECARESERVICES] * [DURATIONDAYS]) / (SUM([HOMECARESERVICES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECAREVISITS' THEN
        SQRT(
            SUM([HOMECAREVISITS]^2) / SUM([HOMECAREVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECAREVISITS] * [DURATIONDAYS]) / (SUM([HOMECAREVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SERVICESPERVISIT' THEN
        SQRT(
            SUM([HOMECARESERVICES]^2) / SUM([HOMECARESERVICES])^2
                + SUM([HOMECAREVISITS]^2) / SUM([HOMECAREVISITS])^2
                - 2 * SUM([HOMECARESERVICES] * [HOMECAREVISITS]) / (SUM([HOMECARESERVICES]) * SUM([HOMECAREVISITS]))
        )
    WHEN 'HOMECAREDAYS' THEN
        SQRT(
            SUM([HOMECAREDAYS]^2) / SUM([HOMECAREDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECAREDAYS] * [DURATIONDAYS]) / (SUM([HOMECAREDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECAREPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([HOMECARESERVICES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([HOMECARESERVICES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([HOMECARESERVICES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([HOMECARESERVICES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECAREPROFESSIONALSERVICES' THEN
        SQRT(
            SUM([HOMECAREPROFESSIONALSERVICES]^2) / SUM([HOMECAREPROFESSIONALSERVICES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECAREPROFESSIONALSERVICES] * [DURATIONDAYS]) / (SUM([HOMECAREPROFESSIONALSERVICES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECAREPROFESSIONALVISITS' THEN
        SQRT(
            SUM([HOMECAREPROFESSIONALVISITS]^2) / SUM([HOMECAREPROFESSIONALVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECAREPROFESSIONALVISITS] * [DURATIONDAYS]) / (SUM([HOMECAREPROFESSIONALVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        SQRT(
            SUM([HOMECAREPROFESSIONALSERVICES]^2) / SUM([HOMECAREPROFESSIONALSERVICES])^2
                + SUM([HOMECAREPROFESSIONALVISITS]^2) / SUM([HOMECAREPROFESSIONALVISITS])^2
                - 2 * SUM([HOMECAREPROFESSIONALSERVICES] * [HOMECAREPROFESSIONALVISITS]) / (SUM([HOMECAREPROFESSIONALSERVICES]) * SUM([HOMECAREPROFESSIONALVISITS]))
        )
    WHEN 'HOMECAREPROFESSIONALDAYS' THEN
        SQRT(
            SUM([HOMECAREPROFESSIONALDAYS]^2) / SUM([HOMECAREPROFESSIONALDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECAREPROFESSIONALDAYS] * [DURATIONDAYS]) / (SUM([HOMECAREPROFESSIONALDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECAREPROFESSIONALPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([HOMECAREPROFESSIONALSERVICES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([HOMECAREPROFESSIONALSERVICES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([HOMECAREPROFESSIONALSERVICES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([HOMECAREPROFESSIONALSERVICES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECARETRANSITIONSERVICES' THEN
        SQRT(
            SUM([HOMECARETRANSITIONSERVICES]^2) / SUM([HOMECARETRANSITIONSERVICES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECARETRANSITIONSERVICES] * [DURATIONDAYS]) / (SUM([HOMECARETRANSITIONSERVICES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECARETRANSITIONVISITS' THEN
        SQRT(
            SUM([HOMECARETRANSITIONVISITS]^2) / SUM([HOMECARETRANSITIONVISITS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECARETRANSITIONVISITS] * [DURATIONDAYS]) / (SUM([HOMECARETRANSITIONVISITS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        SQRT(
            SUM([HOMECARETRANSITIONSERVICES]^2) / SUM([HOMECARETRANSITIONSERVICES])^2
                + SUM([HOMECARETRANSITIONVISITS]^2) / SUM([HOMECARETRANSITIONVISITS])^2
                - 2 * SUM([HOMECARETRANSITIONSERVICES] * [HOMECARETRANSITIONVISITS]) / (SUM([HOMECARETRANSITIONSERVICES]) * SUM([HOMECARETRANSITIONVISITS]))
        )
    WHEN 'HOMECARETRANSITIONDAYS' THEN
        SQRT(
            SUM([HOMECARETRANSITIONDAYS]^2) / SUM([HOMECARETRANSITIONDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([HOMECARETRANSITIONDAYS] * [DURATIONDAYS]) / (SUM([HOMECARETRANSITIONDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'HOMECARETRANSITIONPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([HOMECARETRANSITIONSERVICES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([HOMECARETRANSITIONSERVICES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([HOMECARETRANSITIONSERVICES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([HOMECARETRANSITIONSERVICES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'LABORATORYASSAYS' THEN
        SQRT(
            SUM([LABORATORYASSAYS]^2) / SUM([LABORATORYASSAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LABORATORYASSAYS] * [DURATIONDAYS]) / (SUM([LABORATORYASSAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LABORATORYSITEDAYS' THEN
        SQRT(
            SUM([LABORATORYSITEDAYS]^2) / SUM([LABORATORYSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LABORATORYSITEDAYS] * [DURATIONDAYS]) / (SUM([LABORATORYSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'ASSAYSPERCOLLECTION' THEN
        SQRT(
            SUM([LABORATORYASSAYS]^2) / SUM([LABORATORYASSAYS])^2
                + SUM([LABORATORYSITEDAYS]^2) / SUM([LABORATORYSITEDAYS])^2
                - 2 * SUM([LABORATORYASSAYS] * [LABORATORYSITEDAYS]) / (SUM([LABORATORYSITEDAYS]) * SUM([LABORATORYASSAYS]))
        )
    WHEN 'LABORATORYDAYS' THEN
        SQRT(
            SUM([LABORATORYDAYS]^2) / SUM([LABORATORYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LABORATORYDAYS] * [DURATIONDAYS]) / (SUM([LABORATORYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LABORATORYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([LABORATORYASSAYS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([LABORATORYASSAYS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([LABORATORYASSAYS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([LABORATORYASSAYS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'LONGTERMCAREDAYS' THEN
        SQRT(
            SUM([LONGTERMCAREDAYS]^2) / SUM([LONGTERMCAREDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LONGTERMCAREDAYS] * [DURATIONDAYS]) / (SUM([LONGTERMCAREDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LONGTERMCAREADMISSIONS' THEN
        SQRT(
            SUM([LONGTERMCAREADMISSIONS]^2) / SUM([LONGTERMCAREADMISSIONS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LONGTERMCAREADMISSIONS] * [DURATIONDAYS]) / (SUM([LONGTERMCAREADMISSIONS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LONGTERMCAREDISCHARGES' THEN
        SQRT(
            SUM([LONGTERMCAREDISCHARGES]^2) / SUM([LONGTERMCAREDISCHARGES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LONGTERMCAREDISCHARGES] * [DURATIONDAYS]) / (SUM([LONGTERMCAREDISCHARGES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        SQRT(
            SUM([LONGTERMCAREDAYS]^2) / SUM([LONGTERMCAREDAYS])^2
                + SUM([LONGTERMCAREDISCHARGES]^2) / SUM([LONGTERMCAREDISCHARGES])^2
                - 2 * SUM([LONGTERMCAREDAYS] * [LONGTERMCAREDISCHARGES]) / (SUM([LONGTERMCAREDAYS]) * SUM([LONGTERMCAREDISCHARGES]))
        )
    WHEN 'LONGTERMCARESTAYS' THEN
        SQRT(
            SUM([LONGTERMCARESTAYS]^2) / SUM([LONGTERMCARESTAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([LONGTERMCARESTAYS] * [DURATIONDAYS]) / (SUM([LONGTERMCARESTAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'LONGTERMCAREPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([LONGTERMCARESTAYS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([LONGTERMCARESTAYS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([LONGTERMCARESTAYS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([LONGTERMCARESTAYS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYDAILYDOSES' THEN
        SQRT(
            SUM([PHARMACYDAILYDOSES]^2) / SUM([PHARMACYDAILYDOSES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYDAILYDOSES] * [DURATIONDAYS]) / (SUM([PHARMACYDAILYDOSES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYTHERAPEUTICS' THEN
        SQRT(
            SUM([PHARMACYTHERAPEUTICS]^2) / SUM([PHARMACYTHERAPEUTICS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYTHERAPEUTICS] * [DURATIONDAYS]) / (SUM([PHARMACYTHERAPEUTICS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'DOSESPERTHERAPY' THEN
        SQRT(
            SUM([PHARMACYDAILYDOSES]^2) / SUM([PHARMACYDAILYDOSES])^2
                + SUM([PHARMACYTHERAPEUTICS]^2) / SUM([PHARMACYTHERAPEUTICS])^2
                - 2 * SUM([PHARMACYDAILYDOSES] * [PHARMACYTHERAPEUTICS]) / (SUM([PHARMACYDAILYDOSES]) * SUM([PHARMACYTHERAPEUTICS]))
        )
    WHEN 'ALLDOSESPERDISPENSEDPERSON' THEN
        SQRT(
            SUM([PHARMACYDAILYDOSES]^2) / SUM([PHARMACYDAILYDOSES])^2
                + SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                - 2 * SUM([PHARMACYDAILYDOSES] * IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) / (SUM([PHARMACYDAILYDOSES]) * SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)))
        )
    WHEN 'PHARMACYSITEDAYS' THEN
        SQRT(
            SUM([PHARMACYSITEDAYS]^2) / SUM([PHARMACYSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYSITEDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYDAYS' THEN
        SQRT(
            SUM([PHARMACYDAYS]^2) / SUM([PHARMACYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYPERCENTDISPENSED' THEN
        SQRT(
            SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYSTANDARDDAILYDOSES' THEN
        SQRT(
            SUM([PHARMACYSTANDARDDAILYDOSES]^2) / SUM([PHARMACYSTANDARDDAILYDOSES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYSTANDARDDAILYDOSES] * [DURATIONDAYS]) / (SUM([PHARMACYSTANDARDDAILYDOSES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYSTANDARDTHERAPEUTICS' THEN
        SQRT(
            SUM([PHARMACYSTANDARDTHERAPEUTICS]^2) / SUM([PHARMACYSTANDARDTHERAPEUTICS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYSTANDARDTHERAPEUTICS] * [DURATIONDAYS]) / (SUM([PHARMACYSTANDARDTHERAPEUTICS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        SQRT(
            SUM([PHARMACYSTANDARDDAILYDOSES]^2) / SUM([PHARMACYSTANDARDDAILYDOSES])^2
                + SUM([PHARMACYSTANDARDTHERAPEUTICS]^2) / SUM([PHARMACYSTANDARDTHERAPEUTICS])^2
                - 2 * SUM([PHARMACYSTANDARDDAILYDOSES] * [PHARMACYSTANDARDTHERAPEUTICS]) / (SUM([PHARMACYSTANDARDDAILYDOSES]) * SUM([PHARMACYSTANDARDTHERAPEUTICS]))
        )
    WHEN 'STANDARDDOSESPERDISPENSEDPERSON' THEN
        SQRT(
            SUM([PHARMACYSTANDARDDAILYDOSES]^2) / SUM([PHARMACYSTANDARDDAILYDOSES])^2
                + SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                - 2 * SUM([PHARMACYSTANDARDDAILYDOSES] * IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) / (SUM([PHARMACYSTANDARDDAILYDOSES]) * SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)))
        )
    WHEN 'PHARMACYSTANDARDSITEDAYS' THEN
        SQRT(
            SUM([PHARMACYSTANDARDSITEDAYS]^2) / SUM([PHARMACYSTANDARDSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYSTANDARDSITEDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYSTANDARDSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYSTANDARDDAYS' THEN
        SQRT(
            SUM([PHARMACYSTANDARDDAYS]^2) / SUM([PHARMACYSTANDARDDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYSTANDARDDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYSTANDARDDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYPERCENTDISPENSEDSTANDARD' THEN
        SQRT(
            SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYCONTROLLEDDAILYDOSES' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDDAILYDOSES]^2) / SUM([PHARMACYCONTROLLEDDAILYDOSES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYCONTROLLEDDAILYDOSES] * [DURATIONDAYS]) / (SUM([PHARMACYCONTROLLEDDAILYDOSES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYCONTROLLEDTHERAPEUTICS' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDTHERAPEUTICS]^2) / SUM([PHARMACYCONTROLLEDTHERAPEUTICS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYCONTROLLEDTHERAPEUTICS] * [DURATIONDAYS]) / (SUM([PHARMACYCONTROLLEDTHERAPEUTICS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDDAILYDOSES]^2) / SUM([PHARMACYCONTROLLEDDAILYDOSES])^2
                + SUM([PHARMACYCONTROLLEDTHERAPEUTICS]^2) / SUM([PHARMACYCONTROLLEDTHERAPEUTICS])^2
                - 2 * SUM([PHARMACYCONTROLLEDDAILYDOSES] * [PHARMACYCONTROLLEDTHERAPEUTICS]) / (SUM([PHARMACYCONTROLLEDDAILYDOSES]) * SUM([PHARMACYCONTROLLEDTHERAPEUTICS]))
        )
    WHEN 'CONTROLLEDDOSESPERDISPENSEDPERSON' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDDAILYDOSES]^2) / SUM([PHARMACYCONTROLLEDDAILYDOSES])^2
                + SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                - 2 * SUM([PHARMACYCONTROLLEDDAILYDOSES] * IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) / (SUM([PHARMACYCONTROLLEDDAILYDOSES]) * SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)))
        )
    WHEN 'PHARMACYCONTROLLEDSITEDAYS' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDSITEDAYS]^2) / SUM([PHARMACYCONTROLLEDSITEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYCONTROLLEDSITEDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYCONTROLLEDSITEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYCONTROLLEDDAYS' THEN
        SQRT(
            SUM([PHARMACYCONTROLLEDDAYS]^2) / SUM([PHARMACYCONTROLLEDDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PHARMACYCONTROLLEDDAYS] * [DURATIONDAYS]) / (SUM([PHARMACYCONTROLLEDDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PHARMACYPERCENTDISPENSEDCONTROLLED' THEN
        SQRT(
            SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'PRIMARYCAREPROCEDURES' THEN
        SQRT(
            SUM([PRIMARYCAREPROCEDURES]^2) / SUM([PRIMARYCAREPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PRIMARYCAREPROCEDURES] * [DURATIONDAYS]) / (SUM([PRIMARYCAREPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PRIMARYCAREPROVIDERDAYS' THEN
        SQRT(
            SUM([PRIMARYCAREPROVIDERDAYS]^2) / SUM([PRIMARYCAREPROVIDERDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PRIMARYCAREPROVIDERDAYS] * [DURATIONDAYS]) / (SUM([PRIMARYCAREPROVIDERDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERPROVIDER' THEN
        SQRT(
            SUM([PRIMARYCAREPROCEDURES]^2) / SUM([PRIMARYCAREPROCEDURES])^2
                + SUM([PRIMARYCAREPROVIDERDAYS]^2) / SUM([PRIMARYCAREPROVIDERDAYS])^2
                - 2 * SUM([PRIMARYCAREPROCEDURES] * [PRIMARYCAREPROVIDERDAYS]) / (SUM([PRIMARYCAREPROCEDURES]) * SUM([PRIMARYCAREPROVIDERDAYS]))
        )
    WHEN 'PRIMARYCAREDAYS' THEN
        SQRT(
            SUM([PRIMARYCAREDAYS]^2) / SUM([PRIMARYCAREDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PRIMARYCAREDAYS] * [DURATIONDAYS]) / (SUM([PRIMARYCAREDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PRIMARYCAREPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([PRIMARYCAREPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PRIMARYCAREPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([PRIMARYCAREPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([PRIMARYCAREPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'ANESTHESIOLOGYPROCEDURES' THEN
        SQRT(
            SUM([ANESTHESIOLOGYPROCEDURES]^2) / SUM([ANESTHESIOLOGYPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([ANESTHESIOLOGYPROCEDURES] * [DURATIONDAYS]) / (SUM([ANESTHESIOLOGYPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'ANESTHESIOLOGISTSDAYS' THEN
        SQRT(
            SUM([ANESTHESIOLOGISTSDAYS]^2) / SUM([ANESTHESIOLOGISTSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([ANESTHESIOLOGISTSDAYS] * [DURATIONDAYS]) / (SUM([ANESTHESIOLOGISTSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        SQRT(
            SUM([ANESTHESIOLOGYPROCEDURES]^2) / SUM([ANESTHESIOLOGYPROCEDURES])^2
                + SUM([ANESTHESIOLOGISTSDAYS]^2) / SUM([ANESTHESIOLOGISTSDAYS])^2
                - 2 * SUM([ANESTHESIOLOGYPROCEDURES] * [ANESTHESIOLOGISTSDAYS]) / (SUM([ANESTHESIOLOGYPROCEDURES]) * SUM([ANESTHESIOLOGISTSDAYS]))
        )
    WHEN 'ANESTHESIOLOGYDAYS' THEN
        SQRT(
            SUM([ANESTHESIOLOGYDAYS]^2) / SUM([ANESTHESIOLOGYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([ANESTHESIOLOGYDAYS] * [DURATIONDAYS]) / (SUM([ANESTHESIOLOGYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'ANESTHESIOLOGYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([ANESTHESIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([ANESTHESIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([ANESTHESIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([ANESTHESIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'CONSULTPROCEDURES' THEN
        SQRT(
            SUM([CONSULTPROCEDURES]^2) / SUM([CONSULTPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CONSULTPROCEDURES] * [DURATIONDAYS]) / (SUM([CONSULTPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CONSULTPROVIDERDAYS' THEN
        SQRT(
            SUM([CONSULTPROVIDERSDAYS]^2) / SUM([CONSULTPROVIDERSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CONSULTPROVIDERSDAYS] * [DURATIONDAYS]) / (SUM([CONSULTPROVIDERSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERCONSULT' THEN
        SQRT(
            SUM([CONSULTPROCEDURES]^2) / SUM([CONSULTPROCEDURES])^2
                + SUM([CONSULTPROVIDERSDAYS]^2) / SUM([CONSULTPROVIDERSDAYS])^2
                - 2 * SUM([CONSULTPROCEDURES] * [CONSULTPROVIDERSDAYS]) / (SUM([CONSULTPROCEDURES]) * SUM([CONSULTPROVIDERSDAYS]))
        )
    WHEN 'CONSULTDAYS' THEN
        SQRT(
            SUM([CONSULTDAYS]^2) / SUM([CONSULTDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([CONSULTDAYS] * [DURATIONDAYS]) / (SUM([CONSULTDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'CONSULTPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([CONSULTPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([CONSULTPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([CONSULTPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([CONSULTPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'GENERALPRACTICEPROCEDURES' THEN
        SQRT(
            SUM([GENERALPRACTICEPROCEDURES]^2) / SUM([GENERALPRACTICEPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([GENERALPRACTICEPROCEDURES] * [DURATIONDAYS]) / (SUM([GENERALPRACTICEPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'GENERALPRACTITIONERSDAYS' THEN
        SQRT(
            SUM([GENERALPRACTITIONERSDAYS]^2) / SUM([GENERALPRACTITIONERSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([GENERALPRACTITIONERSDAYS] * [DURATIONDAYS]) / (SUM([GENERALPRACTITIONERSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        SQRT(
            SUM([GENERALPRACTICEPROCEDURES]^2) / SUM([GENERALPRACTICEPROCEDURES])^2
                + SUM([GENERALPRACTITIONERSDAYS]^2) / SUM([GENERALPRACTITIONERSDAYS])^2
                - 2 * SUM([GENERALPRACTICEPROCEDURES] * [GENERALPRACTITIONERSDAYS]) / (SUM([GENERALPRACTICEPROCEDURES]) * SUM([GENERALPRACTITIONERSDAYS]))
        )
    WHEN 'GENERALPRACTICEDAYS' THEN
        SQRT(
            SUM([GENERALPRACTICEDAYS]^2) / SUM([GENERALPRACTICEDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([GENERALPRACTICEDAYS] * [DURATIONDAYS]) / (SUM([GENERALPRACTICEDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'GENERALPRACTICEPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([GENERALPRACTICEPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([GENERALPRACTICEPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([GENERALPRACTICEPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([GENERALPRACTICEPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'OBSTETRICPROCEDURES' THEN
        SQRT(
            SUM([OBSTETRICPROCEDURES]^2) / SUM([OBSTETRICPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([OBSTETRICPROCEDURES] * [DURATIONDAYS]) / (SUM([OBSTETRICPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'OBSTETRICIANSDAYS' THEN
        SQRT(
            SUM([OBSTETRICIANSDAYS]^2) / SUM([OBSTETRICIANSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([OBSTETRICIANSDAYS] * [DURATIONDAYS]) / (SUM([OBSTETRICIANSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        SQRT(
            SUM([OBSTETRICPROCEDURES]^2) / SUM([OBSTETRICPROCEDURES])^2
                + SUM([OBSTETRICIANSDAYS]^2) / SUM([OBSTETRICIANSDAYS])^2
                - 2 * SUM([OBSTETRICPROCEDURES] * [OBSTETRICIANSDAYS]) / (SUM([OBSTETRICPROCEDURES]) * SUM([OBSTETRICIANSDAYS]))
        )
    WHEN 'OBSTETRICDAYS' THEN
        SQRT(
            SUM([OBSTETRICDAYS]^2) / SUM([OBSTETRICDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([OBSTETRICDAYS] * [DURATIONDAYS]) / (SUM([OBSTETRICDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'OBSTETRICPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([OBSTETRICPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([OBSTETRICPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([OBSTETRICPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([OBSTETRICPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'PATHOLOGYPROCEDURES' THEN
        SQRT(
            SUM([PATHOLOGYPROCEDURES]^2) / SUM([PATHOLOGYPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PATHOLOGYPROCEDURES] * [DURATIONDAYS]) / (SUM([PATHOLOGYPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PATHOLOGISTSDAYS' THEN
        SQRT(
            SUM([PATHOLOGISTSDAYS]^2) / SUM([PATHOLOGISTSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PATHOLOGISTSDAYS] * [DURATIONDAYS]) / (SUM([PATHOLOGISTSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        SQRT(
            SUM([PATHOLOGYPROCEDURES]^2) / SUM([PATHOLOGYPROCEDURES])^2
                + SUM([PATHOLOGISTSDAYS]^2) / SUM([PATHOLOGISTSDAYS])^2
                - 2 * SUM([PATHOLOGYPROCEDURES] * [PATHOLOGISTSDAYS]) / (SUM([PATHOLOGYPROCEDURES]) * SUM([PATHOLOGISTSDAYS]))
        )
    WHEN 'PATHOLOGYDAYS' THEN
        SQRT(
            SUM([PATHOLOGYDAYS]^2) / SUM([PATHOLOGYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([PATHOLOGYDAYS] * [DURATIONDAYS]) / (SUM([PATHOLOGYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PATHOLOGYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([PATHOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([PATHOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([PATHOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([PATHOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'RADIOLOGYPROCEDURES' THEN
        SQRT(
            SUM([RADIOLOGYPROCEDURES]^2) / SUM([RADIOLOGYPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([RADIOLOGYPROCEDURES] * [DURATIONDAYS]) / (SUM([RADIOLOGYPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'RADIOLOGISTSDAYS' THEN
        SQRT(
            SUM([RADIOLOGISTSDAYS]^2) / SUM([RADIOLOGISTSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([RADIOLOGISTSDAYS] * [DURATIONDAYS]) / (SUM([RADIOLOGISTSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        SQRT(
            SUM([RADIOLOGYPROCEDURES]^2) / SUM([RADIOLOGYPROCEDURES])^2
                + SUM([RADIOLOGISTSDAYS]^2) / SUM([RADIOLOGISTSDAYS])^2
                - 2 * SUM([RADIOLOGYPROCEDURES] * [RADIOLOGISTSDAYS]) / (SUM([RADIOLOGYPROCEDURES]) * SUM([RADIOLOGISTSDAYS]))
        )
    WHEN 'RADIOLOGYDAYS' THEN
        SQRT(
            SUM([RADIOLOGYDAYS]^2) / SUM([RADIOLOGYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([RADIOLOGYDAYS] * [DURATIONDAYS]) / (SUM([RADIOLOGYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'RADIOLOGYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([RADIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([RADIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([RADIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([RADIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'SPECIALTYPROCEDURES' THEN
        SQRT(
            SUM([SPECIALTYPROCEDURES]^2) / SUM([SPECIALTYPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SPECIALTYPROCEDURES] * [DURATIONDAYS]) / (SUM([SPECIALTYPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SPECIALISTSDAYS' THEN
        SQRT(
            SUM([SPECIALISTSDAYS]^2) / SUM([SPECIALISTSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SPECIALISTSDAYS] * [DURATIONDAYS]) / (SUM([SPECIALISTSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        SQRT(
            SUM([SPECIALTYPROCEDURES]^2) / SUM([SPECIALTYPROCEDURES])^2
                + SUM([SPECIALISTSDAYS]^2) / SUM([SPECIALISTSDAYS])^2
                - 2 * SUM([SPECIALTYPROCEDURES] * [SPECIALISTSDAYS]) / (SUM([SPECIALTYPROCEDURES]) * SUM([SPECIALISTSDAYS]))
        )
    WHEN 'SPECIALTYDAYS' THEN
        SQRT(
            SUM([SPECIALTYDAYS]^2) / SUM([SPECIALTYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SPECIALTYDAYS] * [DURATIONDAYS]) / (SUM([SPECIALTYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SPECIALTYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([SPECIALTYPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([SPECIALTYPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([SPECIALTYPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([SPECIALTYPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'SURGICALPROCEDURES' THEN
        SQRT(
            SUM([SURGICALPROCEDURES]^2) / SUM([SURGICALPROCEDURES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SURGICALPROCEDURES] * [DURATIONDAYS]) / (SUM([SURGICALPROCEDURES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SURGEONSDAYS' THEN
        SQRT(
            SUM([SURGEONSDAYS]^2) / SUM([SURGEONSDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SURGEONSDAYS] * [DURATIONDAYS]) / (SUM([SURGEONSDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'PROCEDURESPERSURGEON' THEN
        SQRT(
            SUM([SURGICALPROCEDURES]^2) / SUM([SURGICALPROCEDURES])^2
                + SUM([SURGEONSDAYS]^2) / SUM([SURGEONSDAYS])^2
                - 2 * SUM([SURGICALPROCEDURES] * [SURGEONSDAYS]) / (SUM([SURGICALPROCEDURES]) * SUM([SURGEONSDAYS]))
        )
    WHEN 'SURGERYDAYS' THEN
        SQRT(
            SUM([SURGERYDAYS]^2) / SUM([SURGERYDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SURGERYDAYS] * [DURATIONDAYS]) / (SUM([SURGERYDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SURGERYPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([SURGICALPROCEDURES] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([SURGICALPROCEDURES] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([SURGICALPROCEDURES] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([SURGICALPROCEDURES] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    WHEN 'SUPPORTIVELIVINGDAYS' THEN
        SQRT(
            SUM([SUPPORTIVELIVINGDAYS]^2) / SUM([SUPPORTIVELIVINGDAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SUPPORTIVELIVINGDAYS] * [DURATIONDAYS]) / (SUM([SUPPORTIVELIVINGDAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SUPPORTIVELIVINGADMISSIONS' THEN
        SQRT(
            SUM([SUPPORTIVELIVINGADMISSIONS]^2) / SUM([SUPPORTIVELIVINGADMISSIONS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SUPPORTIVELIVINGADMISSIONS] * [DURATIONDAYS]) / (SUM([SUPPORTIVELIVINGADMISSIONS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SUPPORTIVELIVINGDISCHARGES' THEN
        SQRT(
            SUM([SUPPORTIVELIVINGDISCHARGES]^2) / SUM([SUPPORTIVELIVINGDISCHARGES])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SUPPORTIVELIVINGDISCHARGES] * [DURATIONDAYS]) / (SUM([SUPPORTIVELIVINGDISCHARGES]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        SQRT(
            SUM([SUPPORTIVELIVINGDAYS]^2) / SUM([SUPPORTIVELIVINGDAYS])^2
                + SUM([SUPPORTIVELIVINGDISCHARGES]^2) / SUM([SUPPORTIVELIVINGDISCHARGES])^2
                - 2 * SUM([SUPPORTIVELIVINGDAYS] * [SUPPORTIVELIVINGDISCHARGES]) / (SUM([SUPPORTIVELIVINGDAYS]) * SUM([SUPPORTIVELIVINGDISCHARGES]))
        )
    WHEN 'SUPPORTIVELIVINGSTAYS' THEN
        SQRT(
            SUM([SUPPORTIVELIVINGSTAYS]^2) / SUM([SUPPORTIVELIVINGSTAYS])^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM([SUPPORTIVELIVINGSTAYS] * [DURATIONDAYS]) / (SUM([SUPPORTIVELIVINGSTAYS]) * SUM([DURATIONDAYS]))
        )
    WHEN 'SUPPORTIVELIVINGPERCENTUTILIZATION' THEN
        SQRT(
            SUM(IIF([SUPPORTIVELIVINGSTAYS] > 0, [DURATIONDAYS], 0)^2) / SUM(IIF([SUPPORTIVELIVINGSTAYS] > 0, [DURATIONDAYS], 0))^2
                + SUM([DURATIONDAYS]^2) / SUM([DURATIONDAYS])^2
                - 2 * SUM(IIF([SUPPORTIVELIVINGSTAYS] > 0, [DURATIONDAYS], 0) * [DURATIONDAYS]) / (SUM(IIF([SUPPORTIVELIVINGSTAYS] > 0, [DURATIONDAYS], 0)) * SUM([DURATIONDAYS]))
        )
    ELSE
        0.0
END