SELECT
CASE [hazardrate]
    WHEN 'AMBULATORYMINUTES' THEN
        60 * [DURATIONDAYS]
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        60 * [AMBULATORYVISITS]
    WHEN 'AMBULATORYPRIVATEMINUTES' THEN
        60 * [DURATIONDAYS]
    WHEN 'AMBULATORYPRIVATELENGTHOFSTAY' THEN
        60 * [AMBULATORYPRIVATEVISITS]
    WHEN 'AMBULATORYWORKMINUTES' THEN
        60 * [DURATIONDAYS]
    WHEN 'AMBULATORYWORKLENGTHOFSTAY' THEN
        60 * [AMBULATORYWORKVISITS]
    WHEN 'INPATIENTDISCHARGES' THEN
        [INPATIENTDAYS]
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        [INPATIENTDISCHARGES]
    WHEN 'INPATIENTPRIVATEDISCHARGES' THEN
        [INPATIENTPRIVATEDAYS]
    WHEN 'INPATIENTPRIVATELENGTHOFSTAY' THEN
        [INPATIENTPRIVATEDISCHARGES]
    WHEN 'INPATIENTWORKDISCHARGES' THEN
        [INPATIENTWORKDAYS]
    WHEN 'INPATIENTWORKLENGTHOFSTAY' THEN
        [INPATIENTWORKDISCHARGES]
    WHEN 'CAREMANAGERRELEASES' THEN
        [CAREMANAGERDAYS]
    WHEN 'CAREMANAGERLENGTH' THEN
        [CAREMANAGERRELEASES]
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    WHEN 'SERVICESPERVISIT' THEN
        [HOMECAREVISITS]
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        [HOMECAREPROFESSIONALVISITS]
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        [HOMECARETRANSITIONVISITS]
    WHEN 'ASSAYSPERCOLLECTION' THEN
        [LABORATORYSITEDAYS]
    WHEN 'LONGTERMCAREDISCHARGES' THEN
        [LONGTERMCAREDAYS]
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        [LONGTERMCAREDISCHARGES]
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    WHEN 'DOSESPERTHERAPY' THEN
        [PHARMACYTHERAPEUTICS]
    WHEN 'ALLDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        [PHARMACYSTANDARDTHERAPEUTICS]
    WHEN 'STANDARDDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        [PHARMACYCONTROLLEDTHERAPEUTICS]
    WHEN 'CONTROLLEDDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'PROCEDURESPERPROVIDER' THEN
        [PRIMARYCAREPROVIDERDAYS]
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        [ANESTHESIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERCONSULT' THEN
        [CONSULTPROVIDERSDAYS]
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        [GENERALPRACTITIONERSDAYS]

    WHEN 'PROCEDURESPERGERIATRICIAN' THEN
        [GERIATRICIANSDAYS]

    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        [OBSTETRICIANSDAYS]
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        [PATHOLOGISTSDAYS]

    WHEN 'PROCEDURESPERPEDIATRICIAN' THEN
        [PEDIATRICIANSDAYS]

    WHEN 'PROCEDURESPERPEDIATRICSURGEON' THEN
        [PEDIATRICSURGEONSDAYS]

    WHEN 'PROCEDURESPERPSYCHIATRIST' THEN
        [PSYCHIATRISTSDAYS]
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        [RADIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        [SPECIALISTSDAYS]
    WHEN 'PROCEDURESPERSURGEON' THEN
        [SURGEONSDAYS]
    WHEN 'SUPPORTIVELIVINGDISCHARGES' THEN
        [SUPPORTIVELIVINGDAYS]
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        [SUPPORTIVELIVINGDISCHARGES]
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    ELSE
        [DURATIONDAYS]
END