SELECT
CASE [hazardrate]
    WHEN 'INTERVALDECEASED' THEN
        1000 
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INTERVALDECEASED]
    WHEN 'INTERVALEMIGRATE' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INTERVALEMIGRATE]
    WHEN 'LIVENEWBORNS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LIVENEWBORNS]
    WHEN 'AMBULATORYMINUTES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYMINUTES]
    WHEN 'AMBULATORYVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYVISITS]
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        [AMBULATORYMINUTES]
    WHEN 'AMBULATORYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYSITEDAYS]
    WHEN 'AMBULATORYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYDAYS]
    WHEN 'AMBULATORYPRIVATEMINUTES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYPRIVATEMINUTES]
    WHEN 'AMBULATORYPRIVATEVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYPRIVATEVISITS]
    WHEN 'AMBULATORYPRIVATELENGTHOFSTAY' THEN
        [AMBULATORYPRIVATEMINUTES]
    WHEN 'AMBULATORYPRIVATESITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYPRIVATESITEDAYS]
    WHEN 'AMBULATORYPRIVATEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYPRIVATEDAYS]
    WHEN 'AMBULATORYWORKMINUTES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYWORKMINUTES]
    WHEN 'AMBULATORYWORKVISITS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYWORKVISITS]
    WHEN 'AMBULATORYWORKLENGTHOFSTAY' THEN
        [AMBULATORYWORKMINUTES]
    WHEN 'AMBULATORYWORKSITEDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYWORKSITEDAYS]
    WHEN 'AMBULATORYWORKDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYWORKDAYS]
    WHEN 'INPATIENTDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTDAYS]
    WHEN 'INPATIENTADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTADMISSIONS]
    WHEN 'INPATIENTDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTDISCHARGES]
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        [INPATIENTDAYS]
    WHEN 'INPATIENTSTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTSTAYS]
    WHEN 'INPATIENTPRIVATEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTPRIVATEDAYS]
    WHEN 'INPATIENTPRIVATEADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTPRIVATEADMISSIONS]
    WHEN 'INPATIENTPRIVATEDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTPRIVATEDISCHARGES]
    WHEN 'INPATIENTPRIVATELENGTHOFSTAY' THEN
        [INPATIENTPRIVATEDAYS]
    WHEN 'INPATIENTPRIVATESTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTPRIVATESTAYS]
    WHEN 'INPATIENTWORKDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTWORKDAYS]
    WHEN 'INPATIENTWORKADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTWORKADMISSIONS]
    WHEN 'INPATIENTWORKDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTWORKDISCHARGES]
    WHEN 'INPATIENTWORKLENGTHOFSTAY' THEN
        [INPATIENTWORKDAYS]
    WHEN 'INPATIENTWORKSTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTWORKSTAYS]
    WHEN 'CAREMANAGERDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERDAYS]
    WHEN 'CAREMANAGERALLOCATIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERALLOCATIONS]
    WHEN 'CAREMANAGERRELEASES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERRELEASES]
    WHEN 'CAREMANAGERLENGTH' THEN
        [CAREMANAGERDAYS]
    WHEN 'CAREMANAGERS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERS]
    WHEN 'HOMECARESERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARESERVICES]
    WHEN 'HOMECAREVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREVISITS]
    WHEN 'SERVICESPERVISIT' THEN
        [HOMECARESERVICES]
    WHEN 'HOMECAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREDAYS]
    WHEN 'HOMECAREPROFESSIONALSERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALSERVICES]
    WHEN 'HOMECAREPROFESSIONALVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALVISITS]
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        [HOMECAREPROFESSIONALSERVICES]
    WHEN 'HOMECAREPROFESSIONALDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALDAYS]
    WHEN 'HOMECARETRANSITIONSERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONSERVICES]
    WHEN 'HOMECARETRANSITIONVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONVISITS]
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        [HOMECARETRANSITIONSERVICES]
    WHEN 'HOMECARETRANSITIONDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONDAYS]
    WHEN 'LABORATORYASSAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYASSAYS]
    WHEN 'LABORATORYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYSITEDAYS]
    WHEN 'ASSAYSPERCOLLECTION' THEN
        [LABORATORYASSAYS]
    WHEN 'LABORATORYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYDAYS]
    WHEN 'LONGTERMCAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREDAYS]
    WHEN 'LONGTERMCAREADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREADMISSIONS]
    WHEN 'LONGTERMCAREDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREDISCHARGES]
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        [LONGTERMCAREDAYS]
    WHEN 'LONGTERMCARESTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCARESTAYS]
    WHEN 'PHARMACYDAILYDOSES' THEN
        [PHARMACYDAILYDOSES]
    WHEN 'PHARMACYTHERAPEUTICS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYTHERAPEUTICS]
    WHEN 'DOSESPERTHERAPY' THEN
        [PHARMACYDAILYDOSES]
    WHEN 'PHARMACYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSITEDAYS]
    WHEN 'PHARMACYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYDAYS]
    WHEN 'PHARMACYSTANDARDDAILYDOSES' THEN
        [PHARMACYSTANDARDDAILYDOSES]
    WHEN 'PHARMACYSTANDARDTHERAPEUTICS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDTHERAPEUTICS]
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        [PHARMACYSTANDARDDAILYDOSES]
    WHEN 'PHARMACYSTANDARDSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDSITEDAYS]
    WHEN 'PHARMACYSTANDARDDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDDAYS]
    WHEN 'PHARMACYCONTROLLEDDAILYDOSES' THEN
        1000
            * [PHARMACYCONTROLLEDDAILYDOSES]
    WHEN 'PHARMACYCONTROLLEDTHERAPEUTICS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDTHERAPEUTICS]
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        [PHARMACYCONTROLLEDDAILYDOSES]
    WHEN 'PHARMACYCONTROLLEDSITEDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDSITEDAYS]
    WHEN 'PHARMACYCONTROLLEDDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDDAYS]
    WHEN 'PRIMARYCAREPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREPROCEDURES]
    WHEN 'PRIMARYCAREPROVIDERDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREPROVIDERDAYS]
    WHEN 'PROCEDURESPERPROVIDER' THEN
        [PRIMARYCAREPROCEDURES]
    WHEN 'PRIMARYCAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREDAYS]
    WHEN 'ANESTHESIOLOGYPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGYPROCEDURES]
    WHEN 'ANESTHESIOLOGISTSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        [ANESTHESIOLOGYPROCEDURES]
    WHEN 'ANESTHESIOLOGYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGYDAYS]
    WHEN 'CONSULTPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTPROCEDURES]
    WHEN 'CONSULTPROVIDERDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTPROVIDERSDAYS]
    WHEN 'PROCEDURESPERCONSULT' THEN
        [CONSULTPROCEDURES]
    WHEN 'CONSULTDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTDAYS]
    WHEN 'GENERALPRACTICEPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTICEPROCEDURES]
    WHEN 'GENERALPRACTITIONERSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTITIONERSDAYS]
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        [GENERALPRACTICEPROCEDURES]
    WHEN 'GENERALPRACTICEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTICEDAYS]
    WHEN 'OBSTETRICPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICPROCEDURES]
    WHEN 'OBSTETRICIANSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICIANSDAYS]
    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        [OBSTETRICPROCEDURES]
    WHEN 'OBSTETRICDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICDAYS]
    WHEN 'PATHOLOGYPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGYPROCEDURES]
    WHEN 'PATHOLOGISTSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGISTSDAYS]
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        [PATHOLOGYPROCEDURES]
    WHEN 'PATHOLOGYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGYDAYS]
    WHEN 'RADIOLOGYPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGYPROCEDURES]
    WHEN 'RADIOLOGISTSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        [RADIOLOGYPROCEDURES]
    WHEN 'RADIOLOGYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGYDAYS]
    WHEN 'SPECIALTYPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALTYPROCEDURES]
    WHEN 'SPECIALISTSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALISTSDAYS]
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        [SPECIALTYPROCEDURES]
    WHEN 'SPECIALTYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALTYDAYS]
    WHEN 'SURGICALPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGICALPROCEDURES]
    WHEN 'SURGEONSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGEONSDAYS]
    WHEN 'PROCEDURESPERSURGEON' THEN
        [SURGICALPROCEDURES]
    WHEN 'SURGERYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGERYDAYS]
    WHEN 'SUPPORTIVELIVINGDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGDAYS]
    WHEN 'SUPPORTIVELIVINGADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGADMISSIONS]
    WHEN 'SUPPORTIVELIVINGDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGDISCHARGES]
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        [SUPPORTIVELIVINGDAYS]
    WHEN 'SUPPORTIVELIVINGSTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGSTAYS]
    ELSE
        0.0
END