SELECT
CASE [hazardrate]
    WHEN 'AMBULATORYMINUTES' THEN
        60 * [DURATIONDAYS]
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        60 * [AMBULATORYVISITS]
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        [INPATIENTDISCHARGES]
    WHEN 'CAREMANAGERLENGTH' THEN
        [CAREMANAGERRELEASES]
    WHEN 'SERVICESPERVISIT' THEN
        [HOMECAREVISITS]
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        [HOMECAREPROFESSIONALVISITS]
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        [HOMECARETRANSITIONVISITS]
    WHEN 'ASSAYSPERCOLLECTION' THEN
        [LABORATORYSITEDAYS]
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        [LONGTERMCAREDISCHARGES]
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    WHEN 'DOSESPERTHERAPY' THEN
        [PHARMACYTHERAPEUTICS]
    WHEN 'ALLDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        [PHARMACYSTANDARDTHERAPEUTICS]
    WHEN 'STANDARDDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        [PHARMACYCONTROLLEDTHERAPEUTICS]
    WHEN 'CONTROLLEDDOSESPERDISPENSEDPERSON' THEN
        IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'PROCEDURESPERPROVIDER' THEN
        [PRIMARYCAREPROVIDERDAYS]
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        [ANESTHESIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERCONSULT' THEN
        [CONSULTPROVIDERSDAYS]
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        [GENERALPRACTITIONERSDAYS]
    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        [OBSTETRICIANSDAYS]
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        [PATHOLOGISTSDAYS]
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        [RADIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        [SPECIALISTSDAYS]
    WHEN 'PROCEDURESPERSURGEON' THEN
        [SURGEONSDAYS]
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        [SUPPORTIVELIVINGDISCHARGES]
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    ELSE
        [DURATIONDAYS]
END