SELECT
CASE [hazardrate]
    WHEN 'INTERVALDECEASED' THEN
        1000 
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INTERVALDECEASED]
    WHEN 'INTERVALEMIGRATE' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INTERVALEMIGRATE]
    WHEN 'AMBULATORYMINUTES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYMINUTES]
    WHEN 'AMBULATORYVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYVISITS]
    WHEN 'AMBULATORYLENGTHOFSTAY' THEN
        [AMBULATORYMINUTES]
    WHEN 'AMBULATORYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYSITEDAYS]
    WHEN 'AMBULATORYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [AMBULATORYDAYS]
    WHEN 'AMBULATORYPERCENTUTILIZATION' THEN
        100
            * IIF([AMBULATORYVISITS] > 0, [DURATIONDAYS], 0)
    WHEN 'INPATIENTDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTDAYS]
    WHEN 'INPATIENTADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTADMISSIONS]
    WHEN 'INPATIENTDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTDISCHARGES]
    WHEN 'INPATIENTLENGTHOFSTAY' THEN
        [INPATIENTDAYS]
    WHEN 'INPATIENTSTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [INPATIENTSTAYS]
    WHEN 'INPATIENTPERCENTUTILIZATION' THEN
        100
            * IIF([INPATIENTSTAYS] > 0, [DURATIONDAYS], 0)
    WHEN 'CAREMANAGERDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERDAYS]
    WHEN 'CAREMANAGERALLOCATIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERALLOCATIONS]
    WHEN 'CAREMANAGERRELEASES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CAREMANAGERRELEASES]
    WHEN 'CAREMANAGERLENGTH' THEN
        [CAREMANAGERDAYS]
    WHEN 'CAREMANAGERS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
    WHEN 'CAREMANAGERPERCENTUTILIZATION' THEN
        100
            * IIF([CAREMANAGERS] > 0, [DURATIONDAYS], 0)
    WHEN 'HOMECARESERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARESERVICES]
    WHEN 'HOMECAREVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREVISITS]
    WHEN 'SERVICESPERVISIT' THEN
        [HOMECARESERVICES]
    WHEN 'HOMECAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREDAYS]
    WHEN 'HOMECAREPERCENTUTILIZATION' THEN
        100
            * IIF([HOMECARESERVICES] > 0, [DURATIONDAYS], 0)
    WHEN 'HOMECAREPROFESSIONALSERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALSERVICES]
    WHEN 'HOMECAREPROFESSIONALVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALVISITS]
    WHEN 'PROFESSIONALSERVICESPERVISIT' THEN
        [HOMECAREPROFESSIONALSERVICES]
    WHEN 'HOMECAREPROFESSIONALDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECAREPROFESSIONALDAYS]
    WHEN 'HOMECAREPROFESSIONALPERCENTUTILIZATION' THEN
        100
            * IIF([HOMECAREPROFESSIONALSERVICES] > 0, [DURATIONDAYS], 0)
    WHEN 'HOMECARETRANSITIONSERVICES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONSERVICES]
    WHEN 'HOMECARETRANSITIONVISITS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONVISITS]
    WHEN 'TRANSITIONSERVICESPERVISIT' THEN
        [HOMECARETRANSITIONSERVICES]
    WHEN 'HOMECARETRANSITIONDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [HOMECARETRANSITIONDAYS]
    WHEN 'HOMECARETRANSITIONPERCENTUTILIZATION' THEN
        100
            * IIF([HOMECARETRANSITIONSERVICES] > 0, [DURATIONDAYS], 0)
    WHEN 'LABORATORYASSAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYASSAYS]
    WHEN 'LABORATORYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYSITEDAYS]
    WHEN 'ASSAYSPERCOLLECTION' THEN
        [LABORATORYASSAYS]
    WHEN 'LABORATORYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LABORATORYDAYS]
    WHEN 'LABORATORYPERCENTUTILIZATION' THEN
        100
            * IIF([LABORATORYASSAYS] > 0, [DURATIONDAYS], 0)
    WHEN 'LONGTERMCAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREDAYS]
    WHEN 'LONGTERMCAREADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREADMISSIONS]
    WHEN 'LONGTERMCAREDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCAREDISCHARGES]
    WHEN 'LONGTERMCARELENGTHOFSTAY' THEN
        [LONGTERMCAREDAYS]
    WHEN 'LONGTERMCARESTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [LONGTERMCARESTAYS]
    WHEN 'LONGTERMCAREPERCENTUTILIZATION' THEN
        100
            * IIF([LONGTERMCARESTAYS] > 0, [DURATIONDAYS], 0)
    WHEN 'PHARMACYDAILYDOSES' THEN
        1000
            * [PHARMACYDAILYDOSES]
    WHEN 'PHARMACYTHERAPEUTICS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYTHERAPEUTICS]
    WHEN 'DOSESPERTHERAPY' THEN
        [PHARMACYDAILYDOSES]
    WHEN 'ALLDOSESPERDISPENSEDPERSON' THEN
        1000
            * [PHARMACYDAILYDOSES]
    WHEN 'PHARMACYSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSITEDAYS]
    WHEN 'PHARMACYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYDAYS]
    WHEN 'PHARMACYPERCENTDISPENSED' THEN
        100
            * IIF([PHARMACYTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'PHARMACYSTANDARDDAILYDOSES' THEN
        1000
            * [PHARMACYSTANDARDDAILYDOSES]
    WHEN 'PHARMACYSTANDARDTHERAPEUTICS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDTHERAPEUTICS]
    WHEN 'DOSESPERSTANDARDTHERAPY' THEN
        [PHARMACYSTANDARDDAILYDOSES]
    WHEN 'STANDARDDOSESPERDISPENSEDPERSON' THEN
        1000
            * [PHARMACYSTANDARDDAILYDOSES]
    WHEN 'PHARMACYSTANDARDSITEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDSITEDAYS]
    WHEN 'PHARMACYSTANDARDDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYSTANDARDDAYS]
    WHEN 'PHARMACYPERCENTDISPENSEDSTANDARD' THEN
        100
            * IIF([PHARMACYSTANDARDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'PHARMACYCONTROLLEDDAILYDOSES' THEN
        1000
            * [PHARMACYCONTROLLEDDAILYDOSES]
    WHEN 'PHARMACYCONTROLLEDTHERAPEUTICS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDTHERAPEUTICS]
    WHEN 'DOSESPERCONTROLLEDTHERAPY' THEN
        [PHARMACYCONTROLLEDDAILYDOSES]
    WHEN 'CONTROLLEDDOSESPERDISPENSEDPERSON' THEN
        1000
            * [PHARMACYCONTROLLEDDAILYDOSES]
    WHEN 'PHARMACYCONTROLLEDSITEDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDSITEDAYS]
    WHEN 'PHARMACYCONTROLLEDDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PHARMACYCONTROLLEDDAYS]
    WHEN 'PHARMACYPERCENTDISPENSEDCONTROLLED' THEN
        100
            * IIF([PHARMACYCONTROLLEDTHERAPEUTICS] > 0, [DURATIONDAYS], 0)
    WHEN 'PRIMARYCAREPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREPROCEDURES]
    WHEN 'PRIMARYCAREPROVIDERDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREPROVIDERDAYS]
    WHEN 'PROCEDURESPERPROVIDER' THEN
        [PRIMARYCAREPROCEDURES]
    WHEN 'PRIMARYCAREDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PRIMARYCAREDAYS]
    WHEN 'PRIMARYCAREPERCENTUTILIZATION' THEN
        100
            * IIF([PRIMARYCAREPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'ANESTHESIOLOGYPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGYPROCEDURES]
    WHEN 'ANESTHESIOLOGISTSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERANESTHESIOLOGIST' THEN
        [ANESTHESIOLOGYPROCEDURES]
    WHEN 'ANESTHESIOLOGYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [ANESTHESIOLOGYDAYS]
    WHEN 'ANESTHESIOLOGYPERCENTUTILIZATION' THEN
        100
            * IIF([ANESTHESIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'CONSULTPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTPROCEDURES]
    WHEN 'CONSULTPROVIDERDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTPROVIDERSDAYS]
    WHEN 'PROCEDURESPERCONSULT' THEN
        [CONSULTPROCEDURES]
    WHEN 'CONSULTDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [CONSULTDAYS]
    WHEN 'CONSULTPERCENTUTILIZATION' THEN
        100
            * IIF([CONSULTPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'GENERALPRACTICEPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTICEPROCEDURES]
    WHEN 'GENERALPRACTITIONERSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTITIONERSDAYS]
    WHEN 'PROCEDURESPERGENERALPRACTITIONER' THEN
        [GENERALPRACTICEPROCEDURES]
    WHEN 'GENERALPRACTICEDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [GENERALPRACTICEDAYS]
    WHEN 'GENERALPRACTICEPERCENTUTILIZATION' THEN
        100
            * IIF([GENERALPRACTICEPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'OBSTETRICPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICPROCEDURES]
    WHEN 'OBSTETRICIANSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICIANSDAYS]
    WHEN 'PROCEDURESPEROBSTETRICIAN' THEN
        [OBSTETRICPROCEDURES]
    WHEN 'OBSTETRICDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [OBSTETRICDAYS]
    WHEN 'OBSTETRICPERCENTUTILIZATION' THEN
        100
            * IIF([OBSTETRICPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'PATHOLOGYPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGYPROCEDURES]
    WHEN 'PATHOLOGISTSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGISTSDAYS]
    WHEN 'PROCEDURESPERPATHOLOGIST' THEN
        [PATHOLOGYPROCEDURES]
    WHEN 'PATHOLOGYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [PATHOLOGYDAYS]
    WHEN 'PATHOLOGYPERCENTUTILIZATION' THEN
        100
            * IIF([PATHOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'RADIOLOGYPROCEDURES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGYPROCEDURES]
    WHEN 'RADIOLOGISTSDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGISTSDAYS]
    WHEN 'PROCEDURESPERRADIOLOGIST' THEN
        [RADIOLOGYPROCEDURES]
    WHEN 'RADIOLOGYDAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [RADIOLOGYDAYS]
    WHEN 'RADIOLOGYPERCENTUTILIZATION' THEN
        100
            * IIF([RADIOLOGYPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'SPECIALTYPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALTYPROCEDURES]
    WHEN 'SPECIALISTSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALISTSDAYS]
    WHEN 'PROCEDURESPERSPECIALIST' THEN
        [SPECIALTYPROCEDURES]
    WHEN 'SPECIALTYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SPECIALTYDAYS]
    WHEN 'SPECIALTYPERCENTUTILIZATION' THEN
        100
            * IIF([SPECIALTYPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'SURGICALPROCEDURES' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGICALPROCEDURES]
    WHEN 'SURGEONSDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGEONSDAYS]
    WHEN 'PROCEDURESPERSURGEON' THEN
        [SURGICALPROCEDURES]
    WHEN 'SURGERYDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SURGERYDAYS]
    WHEN 'SURGERYPERCENTUTILIZATION' THEN
        100
            * IIF([SURGICALPROCEDURES] > 0, [DURATIONDAYS], 0)
    WHEN 'SUPPORTIVELIVINGDAYS' THEN
        (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGDAYS]
    WHEN 'SUPPORTIVELIVINGADMISSIONS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGADMISSIONS]
    WHEN 'SUPPORTIVELIVINGDISCHARGES' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGDISCHARGES]
    WHEN 'SUPPORTIVELIVINGLENGTHOFSTAY' THEN
        [SUPPORTIVELIVINGDAYS]
    WHEN 'SUPPORTIVELIVINGSTAYS' THEN
        1000
            * (1 + DATEDIFF('day', [CENSUSSTART], [CENSUSEND]))
            * [SUPPORTIVELIVINGSTAYS]
    WHEN 'SUPPORTIVELIVINGPERCENTUTILIZATION' THEN
        100
            * IIF([SUPPORTIVELIVINGSTAYS] > 0, [DURATIONDAYS], 0)
    ELSE
        0.0
END